<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>disable</Nullable>
    <AssemblyName>derivetest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\MapleLib\MapleLib\MapleLib.csproj" />
    <ProjectReference Include="..\..\SkillPreview\SkillPreview.csproj" />
  </ItemGroup>
</Project>
